name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: webappcontainerswe40006.azurecr.io   # Replace with your ACR login server (e.g., myregistry.azurecr.io)
        username: ${{ WebAppContainerSWE40006 }}  # Store this in GitHub Secrets
        password: ${{ UserAdminPassword }}  # Store this in GitHub Secrets

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}/my-app:${{ github.sha }} .
        docker push ${{ secrets.ACR_NAME }}/my-app:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: CafeApp   # Replace with your Azure Web App name
        images: ${{ secrets.ACR_NAME }}/my-app:${{ github.sha }}
